name: mask

on:
  workflow_dispatch:

jobs:
  mask:
    runs-on: ubuntu-latest
    steps:
      - name: output
        run: echo "Axel von Engel"
      - name: output secret
        run: echo "${{ secrets.AXEL }} ${{ secrets.SECRET_ONLY }}"
