name: mask

on:
  workflow_dispatch:

jobs:
  mask:
    runs-on: ubuntu-latest
    steps:
      - name: output
        run: echo "Axel von Engel"
      - name: determine secret name
        id: secret_name
        run: echo "::set-output name=secret_name::foo"
      - name: output one secret
        run: echo "${{ secrets[steps.secret_name.outputs.secret_name] }}"
